---
name: Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env:
        description: "Select environment to deploy to"
        type: choice
        required: true
        default: "stage & prod"
        options:
          - stage
          - prod
          - stage & prod
      baseSha:
        description: "Use base SHA commit to deploy from (empty string defaults to last commit before HEAD)"
        type: string
        required: false
        default: ""
      deployAll:
        description: "Force deploy all files"
        type: boolean
        default: false
jobs:
  deployment:
    name: Deployment
    uses: AdobeDocs/adp-devsite-workflow/.github/workflows/deploy.yml@main
    with:
      env: ${{ github.event_name == 'workflow_dispatch' && inputs.env || 'stage' }}
      baseSha: ${{ github.event_name == 'workflow_dispatch' && inputs.baseSha || '' }}
      deployAll: ${{ github.event_name == 'workflow_dispatch' && inputs.deployAll || true }}